// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { AnimatedSprite } from './deca/animated-sprite';
export { Color } from './deca/color';
export { Position } from './deca/position';
export { Sprite } from './deca/sprite';
export { SpriteSheet } from './deca/sprite-sheet';
export { SpriteSheetRoot } from './deca/sprite-sheet-root';
